### ISSUE TITLE
Tripal Daemon Unrecoverable Error (from email)

### ISSUE THREAD

**Issue by mdhar1980** [UofS-Pulse-Binfo/tripal_daemon#9]
Hi, Lacy,

Thanks again for creating the module. I emailed you recently about an issue (unrecoverable error) I had, and you asked me to post an issue here with more information, so doing that now:

1) First, from my original query: "For a site we're building, I installed the module and all the requirements but have not been able to get it to work. Inputting the "drush trpjob-daemon start" command returns an unrecoverable error: "Drush command terminated abnormally due to an unrecoverable error."

I've triple-checked the dependencies and tried various fixes with the underlying Drush Daemon code (which gave more detailed error messages), but have not been able to get the Tripal Daemon to start."

2) The information you requested:

a) Software Versions
- version of Tripal, Tripal Daemon and Drush Daemon
		* Tripal 2.1, Tripal Daemon 7.x-1.0, Drush Daemon 7.x-2.3
		* Tripal Core 7.x-2.1-beta3+22-dev
	- version of the PHP-Daemon library
		* 2.1
	- version of Apache, PHP and Drupal
		* Apache/2.4.10 (Debian)
		* PHP 7.0.3 (cli)
		* Drupal: Drupal 7.42
	- operating system
		* Linux 8d9aef535798 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 GNU/Linux

b) Drush Daemon Error Messages:
 I just made a sample Daemon that's in Drushd itself. Current error messages: 
"
[15-Jan-2018 16:13:24 America/New_York] PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class 'MyModuleDaemon' not found in /var/www/html/sites/all/modules/drushd/includes/drushd.api.inc on line 134 pid 6450
[15-Jan-2018 16:13:24 America/New_York] PHP Warning: call_user_func() expects parameter 1 to be a valid callback, class 'MyModuleDaemon' not found in /var/www/html/sites/all/modules/drushd/includes/drushd.api.inc on line 358 pid 6450
[15-Jan-2018 16:13:24 America/New_York] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to daemon_exception() must be an instance of Exception, instance of Error given in /var/www/html/sites/all/libraries/PHP-Daemon/Core/error_handlers.php:111
Stack trace:
#0 [internal function]: daemon_exception(Object(Error))
#1 {main}
  thrown in /var/www/html/sites/all/libraries/PHP-Daemon/Core/error_handlers.php on line 111
Drush command terminated abnormally due to an unrecoverable error.                                                                                       [error]
Error: Uncaught TypeError: Argument 1 passed to daemon_exception() must be an instance of Exception, instance of Error given in
/var/www/html/sites/all/libraries/PHP-Daemon/Core/error_handlers.php:111
Stack trace:
#0 [internal function]: daemon_exception(Object(Error))
#1 {main}
  thrown in /var/www/html/sites/all/libraries/PHP-Daemon/Core/error_handlers.php, line 111
"

c) apache error log
			* Ran commands for Tripal Daemon and Drush Daemon first...
				* DRUSH:  drush daemon start mymodule_daemon
				* TRIPAL: drush trpjob-daemon start
				* ERROR: Drush command terminated abnormally due to an unrecoverable error.  
			*  In /var/log/apache2/
					* files: access.log  error.log  other_vhosts_access.log
					* all empty

d) Drupal "Recent log messages
			* Nothing recent (after ran daemon commands) in admin/reports/dblog

Thanks again! And please let me know if you need to know anything else.

--Michael Dhar

**Comment by laceysanderson** [comment]
As far as version information goes, everything looks good although I haven't tested with PHP 7 yet (most testing has been done with 5.6.x).

Let's start by double checking that the Drush Daemon module is working properly by using the  example daemon provided by Drush Daemon. Try executing`drush daemon start example`. Does this start normally or do you receive the "unrecoverable error". This is what you should see:

> $ drush daemon start example
>                                                                                            [ok]
> Starting Example Daemon
> Use 'drush daemon status example' to check the status of the daemon just started and 'drush daemon stop example' to stop it.

If you don't get an error, you can check that it is running properly using `drush daemon status example` and `drush daemon show-log example`.

> $ drush daemon status example
> 
> The Daemon is currently running...
> 
> The last known status for this daemon is:
>         PID: 95404
>         Hibernating: FALSE
>         Number of Iterations: 3
>         Current Log File: /tmp/drupal7-DrushDaemonExample_20180124.log
>                                                                                            [ok]
> $ drush daemon show-log example
> [2018-01-24 03:57:50] 95404 NAP           Waking up...
> [2018-01-24 03:57:50] 95404               Now that I've completed all my work, I'm taking a 20 second break until the loop comes around again *smiles*.
> [2018-01-24 03:57:59] 95404               I am really tired *Yawns*! I'm going to task myself with a 14 second nap...
> [2018-01-24 03:57:59] 95404 NAP           Commensing 14 second nap.
> [2018-01-24 03:58:13] 95404 NAP           Waking up...
> [2018-01-24 03:58:13] 95404               Now that I've completed all my work, I'm taking a 20 second break until the loop comes around again *smiles*.
> [2018-01-24 03:58:19] 95404               I am really tired *Yawns*! I'm going to task myself with a 6 second nap...
> [2018-01-24 03:58:19] 95404 NAP           Commensing 6 second nap.
> [2018-01-24 03:58:25] 95404 NAP           Waking up...
> [2018-01-24 03:58:25] 95404               Now that I've completed all my work, I'm taking a 20 second break until the loop comes around again *smiles*.

**Comment by mdhar1980** [comment]
Hi, Lacey,

Thanks for looking into it. I get an error when I run that command, and the same error when running status example or show-log example:

ERROR:

> Use of undefined constant WATCHDOG_WARING - assumed 'WATCHDOG_WARING' drushd.api.inc:55                                                                      [notice]
> PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "WATCHDOG_WARING"                                 [error]
> LINE 1: ...a223a6e616d65223b733a373a226578616d706c65223b7d', 'WATCHDOG_...
>                                                              ^ in /var/www/html/includes/database/database.inc:2171


HERE IS THE FULL OUTPUT:

> Initialized Drupal 7.42 root directory at /var/www/html                                                                                                      [notice]
> Initialized Drupal site default at sites/default                                                                                                             [notice]
> Executing: PGPASSFILE=/tmp/drush_z02G5V psql -q --dbname=drupal --host=172.17.0.8 --port=5432 --username=postgres  --no-align --field-separator='	' --pset tuples_only=on --file /tmp/drush_o3ZkfV
> Executing: PGPASSFILE=/tmp/drush_7YieZX psql -q --dbname=drupal --host=172.17.0.8 --port=5432 --username=postgres  --no-align --field-separator='	' --pset tuples_only=on --file /tmp/drush_YpIr2W
> Use of undefined constant WATCHDOG_WARING - assumed 'WATCHDOG_WARING' drushd.api.inc:55                                                                      [notice]
> PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "WATCHDOG_WARING"                                 [error]
> LINE 1: ...a223a6e616d65223b733a373a226578616d706c65223b7d', 'WATCHDOG_...
>                                                              ^ in /var/www/html/includes/database/database.inc:2171
> Stack trace:
> #0 /var/www/html/includes/database/database.inc(2171): PDOStatement->execute(NULL)
> #1 /var/www/html/includes/database/pgsql/database.inc(106): DatabaseStatementBase->execute(NULL, Array)
> #2 /var/www/html/includes/database/pgsql/query.inc(96): DatabaseConnection_pgsql->query(Object(DatabaseStatementBase), Array, Array)
> #3 /var/www/html/modules/dblog/dblog.module(163): InsertQuery_pgsql->execute()
> #4 /var/www/html/includes/module.inc(922): dblog_watchdog(Array)
> #5 /var/www/html/includes/bootstrap.inc(1740): module_invoke('dblog', 'watchdog', Array)
> #6 /var/www/html/sites/all/modules/drushd/includes/drushd.api.inc(55): watchdog('drushd', 'Daemon :name no...', Array, 'WATCHDOG_WARING')
> #7 /var/www/html/sites/all/modules/drushd/includes/drushd.api.inc(340): drushd_get_daemon_info('example', true)
> #8 /var/www/html/sites/all/modules/drushd/drushd.drush.inc(116): drushd_instantiate_daemon('example')
> #9 /var/www/html/sites/all/modules/drushd/drushd.drush.inc(87): drush_daemon_api_start_daemon('example')
> #10 /root/.composer/vendor/drush/drush/includes/command.inc(359): drush_drushd_daemon('start', 'example')
> #11 /root/.composer/vendor/drush/drush/includes/command.inc(210): _drush_invoke_hooks(Array, Array)
> #12 /root/.composer/vendor/drush/drush/includes/command.inc(178): drush_command('start', 'example')
> #13 /root/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(62): drush_dispatch(Array)
> #14 /root/.composer/vendor/drush/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
> #15 /root/.composer/vendor/drush/drush/drush.php(11): drush_main()
> #16 {main}
> Command dispatch complete

**Comment by mdhar1980** [comment]
Hi, again, Lacey,

I had made some changes to the example module (trying to match the tutorial for the Drush daemon to see if that would work). So, I went back and reset to the defaults, and ran your example daemon command again. This time, I got the same "unrecoverable error" that I did with Tripal.

> Initialized Drupal 7.42 root directory at /var/www/html                                                                                                                 [notice]
> Initialized Drupal site default at sites/default                                                                                                                        [notice]
> Executing: PGPASSFILE=/tmp/drush_a1dO1X psql -q --dbname=drupal --host=172.17.0.8 --port=5432 --username=postgres  --no-align --field-separator='	' --pset tuples_only=on --file /tmp/drush_IDVPYB
> Executing: PGPASSFILE=/tmp/drush_FXrHlG psql -q --dbname=drupal --host=172.17.0.8 --port=5432 --username=postgres  --no-align --field-separator='	' --pset tuples_only=on --file /tmp/drush_tWNJbk
> 
> Drush command terminated abnormally due to an unrecoverable error.                                                                                                   [error]
> 

Thanks again

**Comment by laceysanderson** [comment]
Ok, so that implies your troubles are coming from the Drush Daemon module, not Tripal Daemon. I looked into line 55 of the Drush Daemon API as indicated by this error:

> Use of undefined constant WATCHDOG_WARING - assumed 'WATCHDOG_WARING' drushd.api.inc:55 [notice]
> PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "WATCHDOG_WARING" [error]
> LINE 1: ...a223a6e616d65223b733a373a226578616d706c65223b7d', 'WATCHDOG_...
> ^ in /var/www/html/includes/database/database.inc:2171

And found a small bug which was causing you to not get a useful error message. This warning implied that the "Daemon is not registered. Please implement hook_daemon_api_info() in your module." However, you were running the example daemon which is implemented by the Drush Daemon module itself...

Since I see you have made edits here and there trying to debug, could you please 
1. download a fresh version of the Drush Daemon module, PHP-Daemon library and Tripal Daemon module
2. clear the cache using `drush cc all` **Twice**
3. Run `drush daemon start example` as instructed above.

This will just help me rule out errors caused by any edits to the code making it easier to find the bug causing you issues. Thanks for your patience with this! I have tested multiple times on my own system and am unable to replicate the bug myself.

**Comment by mdhar1980** [comment]
Hi, Lacey,

The Drush Daemon is not eligible to be uninstalled (i.e., the checkbox on modules is not clickable to un-enable it). It is sufficient to simply reinstall?

Thanks

**Comment by laceysanderson** [comment]
It's not eligible to be uninstalled because you have to uninstall Tripal Daemon first (dependencies :-) ). So first uninstall Tripal Daemon, then Drush Daemon, then replace the code with the fresh downloads (both modules and PHP-Daemon library), then re-install both modules. That should get us back to a fresh state.

**Comment by mdhar1980** [comment]
Ah, of course. Thanks! I uninstalled Tripal Daemon, but get an error message when trying to uninstall Drush Daemon:

> Error: Call to undefined function drushd_get_daemon_status_file() in drushd_uninstall() (line 105 of /var/www/html/sites/all/modules/drushd/drushd.install).

I looked into the drushd.install file, and I can't find where that function is meant to be defined. Do you know what's missing?

Thanks

**Comment by mdhar1980** [comment]
Hi, Lacey,

I could not find that missing function in drushd.install, but I reset all code and reinstalled everything else, cleared the cache as you instructed, and ran the command again. I still get the same error:

> Drush command terminated abnormally due to an unrecoverable error.

I should also mention that we are running this developmental version of our site in a Docker setting. In the past, that has meant we had to change some PHP settings to get things working. We haven't found any so far that impact these daemon modules, but I'm mentioning in case you know of any -- or of how to find them.

Thanks again for your help!
--Michael

**Comment by laceysanderson** [comment]
This module has been moved into [Tripal CORE](https://github.com/tripal/tripal/tree/7.x-3.x/tripal_daemon). Please try the new version. If you still encounter errors, please report it on the Tripal Repo.
